---

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
