build:
	docker build -t hexlet/hexlet-exercise-kit .

run:
	docker run -it --read-only -p 8000:8000 hexlet/hexlet-exercise-kit /bin/bash

publish:
	docker push hexlet/hexlet-exercise-kit

.PHONY: build run
