#!/usr/bin/env node

const fs = require('fs');

const data = fs.readFileSync('services.conf', 'utf-8');
const envLine = data.split('\n')
  .filter((l) => l.startsWith('environment'))
  .map((l) => l.replace('environment=', ''))
  .flatMap((l) => l.split(','))
  .filter((kv) => kv.startsWith('X_FORWARDED_'))
  .map((kv) => {
    const [name, value] = kv.split('=');
    const realName = name.replace('X_FORWARDED_', '');
    return `${realName}=${value}`;
  })
  .join(',') || `NO_FORWARDED_VARS=1`;

process.stdout.write(envLine);
